apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-admission-webhook
webhooks:
  - name: webhook.kube-system.svc
    clientConfig:
      caBundle: <ca base64>
      service:
        name: webhook-admission-webhook
        namespace: kube-system
        path: "/add-label"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["PersistentVolumeClaim"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]